### ISSUE TITLE
Question about error handing (+ congrats!)

### ISSUE THREAD

**Issue by kocsismate** [qpautrat/woohoolabs-yin-bundle#23]
Hi @qpautrat,

This is the first time in a long while when I had to use Symfony, so I used this possibility to try out your integration with Yin. The only thing I can say is that it worked like a charm! :) So thanks for your work!

One question came to my mind though: how should exception handling work? Is there an easy way to automatically catch exceptions implementing the `JsonApiExceptionIntererface` and return an error document? If so, then it would be very cool if you could share some details in the readme.

**Comment by Doqnach** [comment]
Symfony just officially released their `ErrorHandling` component that can facilitate in this, starting with Symfony 4.4: https://symfony.com/blog/new-in-symfony-4-4-errorhandler-component

**Comment by kocsismate** [comment]
Yeah, I also saw it. But I thought that it'd might worth a short note in the readme similar to how I did for https://github.com/woohoolabs/yin-middleware#jsonapiexceptionhandlermiddleware . Anyway, I just mainly wanted to say congrats, so I'm closing this ticket and you can decide later whether the note in the readme is really needed.

**Comment by qpautrat** [comment]
Hello @kocsismate 👋 ,

Thank you it's much appreciated.
To be fair I didn't think about it because as it is a Symfony Bundle, I think it should be handled by the framework itself and so it is the responsability of the developer to use adequat mechanisms available in the framework.

**Comment by kocsismate** [comment]
Yes, it makes sense for sure what you say. The only benefit my idea could bring is to help Symfony newbies who are not familiar with the framework.
